SELECT UZYTKOWNIK.*, PRZEDMIOT.NAZWA AS 'PRZEDMIOT' FROM UZYTKOWNIK 
RIGHT JOIN PROWADZI ON PROWADZI.ID_NAUCZYCIELA = UZYTKOWNIK.ID_UZYTKOWNIKA
LEFT JOIN PRZEDMIOT ON PRZEDMIOT.ID_PRZEDMIOTU = PROWADZI.ID_PRZEDMIOTU